app/mypay/forms.py
from flask_wtf import FlaskForm
from wtforms import SubmitField, IntegerField, DateTimeField
from datetime import date
from wtforms.validators import DataRequired

class SaleForm(FlaskForm):
    """
    Form for admin to add or edit a sale
    """
    amount = IntegerField('Amount', validators=[DataRequired()])
    date = DateTimeField("Today", format="%Y-%m-%d", default=date.today(),validators=[DataRequired()])
    submit = SubmitField('Submit')

app/mypay/__init__.py
from flask import Blueprint

mypay = Blueprint('mypay', __name__)

from . import views

app/mypay/views.py
from flask import abort, flash, redirect, render_template, url_for
from flask_login import login_required, current_user
from ..models import Sale, Rate, Employee
from .. import db
from . import mypay
from .forms import SaleForm


def check_admin():
    """
    Prevent non-admins from accessing the page
    """
    if current_user.is_admin:
        abort(403)

@mypay.route('/mypay')
@login_required
def sales():
    """
    Render the dashboard template on the /dashboard route
    """
    # prevent admins from accessing the page
    check_admin()

    employee = Employee.query.get_or_404(current_user.id)
    sales = employee.sales.all()

    return render_template('mypay/mypays.html', sales=sales, employee=employee, title="Earnings")

@mypay.route('/mypay/add', methods=['GET', 'POST'])
@login_required
def add_sale():
    """
    Add a sale to the database
    """
    check_admin()

    add_sale = True
    employee = Employee.query.get_or_404(current_user.id)

    form = SaleForm()
    if form.validate_on_submit():
        sale = Sale(employee=employee, date = form.date.data,
                                amount=form.amount.data, )
        try:
            # add department to the database
            db.session.add(sale)
            db.session.commit()
            flash('You have successfully added a new sale.')
        except:
            # in case department name already exists
            flash('Error: sale already exists.')

        # redirect to departments page
        return redirect(url_for('mypay.sales'))
    return render_template('mypay/mypay.html', action="Add",
                           add_sale=add_sale, form=form,
                           title="Add Sale")

@mypay.route('/mypay/edit/<int:id>', methods=['GET', 'POST'])
@login_required
def edit_sale(id):
    """
    Edit a sale
    """
    check_admin()

    add_sale = False

    sale = Sale.query.get_or_404(id)
    form = SaleForm(obj=sale)
    if form.validate_on_submit():
        sale.amount = form.amount.data
        sale.date = form.date.data
        db.session.commit()
        flash('You have successfully edited the sale.')

        return redirect(url_for('mypay.sales'))

    return render_template('mypay/mypay.html', action="Edit",
                           add_sale=add_sale, form=form,
                           sale=sale, title="Edit Sale")

@mypay.route('/mypay/delete/<int:id>', methods=['GET', 'POST'])
@login_required
def delete_sale(id):
    """
    Delete a sale record from the database
    """
    check_admin()

    sale = Sale.query.get_or_404(id)
    db.session.delete(sale)
    db.session.commit()
    flash('You have successfully deleted the record.')

    return redirect(url_for('mypay.sales'))

    return render_template(title="Delete Record")

app/templates/mypay/mypay.html
<!-- app/templates/admin/departments/department.html -->

{% import "bootstrap/wtf.html" as wtf %}
{% extends "base.html" %}
{% block title %}
    {% if add_sale %}
        Add Sale
    {% else %}
        Edit Sale
    {% endif %}
{% endblock %}
{% block body %}
<div class="content-section">
 <div class="outer">
    <div class="middle">
      <div class="inner">
        <div class="center">
            {% if add_sale %}
                <h1>Add Sale</h1>
            {% else %}
                <h1>Edit Sale</h1>
            {% endif %}
            <br/>
            {{ wtf.quick_form(form) }}
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

app/templates/mypay/mypays.html
<!-- app/templates/admin/departments/departments.html -->

{% import "bootstrap/utils.html" as utils %}
{% extends "base.html" %}
{% block title %}Sales{% endblock %}
{% block body %}
<div class="content-section">
  <div class="outer">
    <div class="middle">
      <div class="inner">
        <br/>
        {{ utils.flashed_messages() }}
        <br/>
        <h1 style="text-align:center;">{{employee.username}}'s Earnings</h1>
        {% if sales %}
          <hr class="intro-divider">
          <div class="center">
            <table class="table table-striped table-bordered">
              <thead>
                <tr>
                  <th width="15%"> Amount </th>
                  <th width="15%"> Date </th>
                  <th width="15%"> Status </th>
                  <th width="15%"> Edit </th>
                  <th width="15%"> Delete </th>
                </tr>
              </thead>
              <tbody>
                {% for sale in sales %}
                    <tr>
                        <td>{{ sale.amount }}</td>
                        <td>{{ sale.date.strftime('%Y-%m-%d') }}</td>
                        <td>{% if sale.is_approved %}Approved{% else %}Pending{% endif %}</td>         
                        <td>
                            {% if not sale.is_approved %}
                                <a href="{{ url_for('mypay.edit_sale', id=sale.id) }}">
                                    <i class="fa fa-pencil"></i> Edit
                                </a>
                            {% else %}
                                <span class="disabled-button">
                                    <i class="fa fa-pencil"></i> Edit
                                </span>
                            {% endif %}
                        </td>
                        <td>
                            {% if not sale.is_approved %}
                                <a href="{{ url_for('mypay.delete_sale', id=sale.id) }}">
                                    <i class="fa fa-trash"></i> Delete
                                </a>
                            {% else %}
                                <span class="disabled-button">
                                    <i class="fa fa-trash"></i> Delete
                                </span>
                            {% endif %}
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
            </table>
          </div>
          <div style="text-align: center">
        {% else %}
          <div style="text-align: center">
            <h3> No sales have been added. </h3>
            <hr class="intro-divider">
        {% endif %}
          <a href="{{ url_for('mypay.add_sale') }}" class="btn btn-default btn-lg">
            <i class="fa fa-plus"></i>
            Add Sale
          </a>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}